FROM ubuntu:18.04

ENV VERSION=18.04 \
    DEBIAN_FRONTEND=noninteractive \
    TZ=Europe/Rome \
    OS=ubuntu
 
COPY bin/tini-static-amd64 bin/dockerize /

RUN echo $TZ > /etc/timezone && \
    apt-get update && apt-get -y dist-upgrade && \
    apt-get install --no-install-recommends -y tzdata locales && \
    rm -rf /var/lib/apt/lists/*

ENV LANG=it_IT.utf8 \
    LANGUAGE=it_IT:it \
    LC_ALL=it_IT.UTF-8

RUN localedef -i it_IT -c -f UTF-8 -A /usr/share/locale/locale.alias it_IT.UTF-8 && \
    echo "it_IT.UTF-8 UTF-8" > /etc/locale.gen && locale-gen && \
    apt-get update && apt-get install --no-install-recommends -y inetutils-ping netcat && \
    rm -rf /var/lib/apt/lists/* && \
    chmod +x /tini-static-amd64 /dockerize && \
    ln -s /tini-static-amd64 /tini 
